### ISSUE TITLE
gruff versus cc-graphs

### ISSUE THREAD

**Issue by rubyFeedback** [AndyObtiva/glimmer-libui-cc-graphs_and_charts#2]
Hey there Andy,

Not sure if you know gruff - I used it first like 15 years ago.

The github repository is, interestingly, active, so the project is not dead:

https://github.com/topfunky/gruff

It shows some examples.

Now, I am not saying cc-graphs should take over all of gruff.

But, specifically, I believe the following two images may be interesting for cc-graphs:

https://camo.githubusercontent.com/b910426c97f54b8127256b4ed14fc393e5524084bd3458b744fa335b2221d3e7/68747470733a2f2f7261772e6769746875622e636f6d2f746f7066756e6b792f67727566662f6d61737465722f746573742f65787065637465642f6261725f7261696c735f6b65796e6f74652e706e67

^^^ the multi-line bar. In the programming language R, this is also sometimes used to compare different datasets concomittantly. (If cc-graphs already supports this then please ignore this.)

The first example you show on the README already shows that single bars can be displayed, so displaying multiple
bars, and ideally also with different colour (for each dataset that is), may be easy to add, so perhaps it would not be
too much work.

The other one, Pastel Pie Graph, is actually also visually nice, since we use one pie chart to describe the dataset:

https://camo.githubusercontent.com/d34c5785f74aba56f63c1a6a2de988e64af76dd5c01f518af97452018a0d6ef1/68747470733a2f2f7261772e6769746875622e636f6d2f746f7066756e6b792f67727566662f6d61737465722f746573742f65787065637465642f7069655f70617374656c2e706e67

Not sure how easy it would be to display that; if you draw onto a drawing area then we just need a circle, and then be able to colourize the inner parts of the circle. Not sure which math is applies here, but I think you also had another project that helps abstract this away, so perhaps this may also be nice to have for cc-graphs. Anyway, this is probably low priority - I just think it would be nice if cc-graphs itself could support this flexibly across all of the glimmer suite, as-is. People may integrate this then in their own applications, if they need to show some statistical data (perhaps even animated, but I think even non-animated statistical display may be useful for people across different applications).

**Comment by AndyObtiva** [comment]
Yeah, I have heard of Gruff, and it is a useful library. One trade-off in using Gruff over graphs/charts rendered directly by Glimmer DSL for LibUI is having a dependency on RMagick, which some developers might not want to have or deal with. When using a Glimmer GUI DSL library that supports displaying images, like Glimmer DSL for GTK, Software Engineers should be able to actually integrate Gruff today by simply having it generate images, and then embedding them in an image control in a Glimmer GUI. So, there is nothing I need to do about this.

Otherwise, I am implementing graphs and charts in this library on a per-need basis, and my current next chart is the Bubble Chart, which I already started working on because I will be using in a real Glimmer DSL for LibUI app soon.

I am closing this ticket, but if you actually do need the Multi-Line Bar Graph and Pie Charts that you shared screenshots of for a real project you are working on, please re-open this ticket and ask me directly for them. I don't want to implement anything just for hypothetical reasons. It is recommended in software to implement things because of a current real need only.
